# Generated by Django 2.1.4 on 2018-12-03 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_auto_20181203_2352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='FormModel',
        ),
    ]
